#!/usr/bin/env perl
use Mojolicious::Lite;


plugin 'PODRenderer';
plugin 'Mambba';

# defaults
#=> {
#   mongodb => 'mongodb://127.0.0.1:27017/',
#   elasticsearch => 'http://localhost:9200/',
#   redis  => '127.0.0.1:27017',
#   prefix   => 'mambba',
#};

app->start;

__DATA__

@@ index.html.ep
Welcome to the Mojolicious real-time web framework!

